// Code generated by ziti-ci. DO NOT EDIT.

package main

const (
	Version   = "v0.5.28"
	Revision  = "2a92db3388ae"
	Branch    = "master"
	BuildUser = "Travis CI User"
	BuildDate = "2020-03-16 19:07:23"
)
