// Code generated by ziti-ci. DO NOT EDIT.

package main

const (
	Version   = "v0.5.31"
	Revision  = "413b97f9946b"
	Branch    = "v1"
	BuildUser = "Travis CI User"
	BuildDate = "2020-04-01 15:27:25"
)
