// Code generated by ziti-ci. DO NOT EDIT.

package main

const (
	Version   = "v0.5.10"
	Revision  = "6e8c60bf6a4c"
	Branch    = "v1"
	BuildUser = "Travis CI User"
	BuildDate = "2020-02-20 21:15:18"
)
