// Code generated by ziti-ci. DO NOT EDIT.

package cmd

const (
	Version   = "v0.5.44"
	Revision  = "b23594654fe8"
	Branch    = "v1"
	BuildUser = "Travis CI User"
	BuildDate = "2020-05-28 18:57:33"
)
