// Code generated by ziti-ci. DO NOT EDIT.

package cmd

const (
	Version   = "v0.5.43"
	Revision  = "c9bc843e9901"
	Branch    = "v1"
	BuildUser = "Travis CI User"
	BuildDate = "2020-05-28 18:53:30"
)
