// Code generated by ziti-ci. DO NOT EDIT.

package cmd

const (
	Version   = "v0.5.38"
	Revision  = "d94a66e5de35"
	Branch    = "v1"
	BuildUser = "Travis CI User"
	BuildDate = "2020-05-27 01:58:00"
)
